# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OTEwNWU0NWMxYWJlNjg1ZmVjMzA3MmJlZGM5N2JkOTVjYzA2NTM1YWRmNmFlMDhjZjU1N2RlZDU3OTdjYzM4MGEwNDczNzg3NmFhOTBhZmRmMjNjZDJjZDY5MDVkZjBmMmM0ZGM4MDE3MzkwZGQ1Y2I1ZjcwZjgyYWVmODAwYWQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
